---
  - hosts: elastic
    become: true

    
    tasks:
      - name: update the apt-get
        apt:
          update_cache: yes

      - name: create ca
        shell:
          chdir:  /usr/share/elasticsearch
          cmd: bin/elasticsearch-certutil ca --out elastic-stack-ca.p12 --pass ""
          
      - name: create cert
        shell:
          chdir:  /usr/share/elasticsearch
          cmd: bin/elasticsearch-certutil cert --silent  --out elastic-certificates.p12 --pass "" elastic-stack-ca.p12

      - name: copy to conf folder
        shell:
          cmd: cp /usr/share/elasticsearch/*.p12 /etc/elasticsearch

      - name: change permission
        shell:
          cmd: chmod 644 /etc/elasticsearch/*.p12

      # - name: keystore
      #   shell:
      #     cmd: bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password -f -x ""

      # - name:  truststore
      #   shell:  
      #     chdir: /usr/share/elasticsearch
      #     cmd: bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password -f -x ""


      - name: copy my elasticsearch file
        copy:
          src: "elasticsearch.yml"
          dest: /etc/elasticsearch/elasticsearch.yml

      - name: Enabling elastic search service
        systemd:
          name: elasticsearch
          enabled: yes
          daemon_reload: yes
# Start Kibana service
      - name: Starting elastic search service
        systemd:
          name: elasticsearch
          state: started
          
      - name: Ensure elastic serach is running
        systemd: state=started name=elasticsearch
        
      # - name: elasticsearch user credentials
      #   shell: 
      #     chdir:  /usr/share/elasticsearch/
      #     cmd:  bin/elasticsearch-setup-passwords auto --silent
      #   register: contents