---
  - hosts: filebeat
    become: true

    
    tasks:
      - name: update the apt-get
        apt:
          update_cache: yes
    
      - name: copy conf file
        copy:
          src: "filebeat.yml"
          dest: /etc/filebeat/filebeat.yml

      - name: enable logstash module
        shell:
          cmd: filebeat modules enable system

      - name: setup piplines
        shell:
          cmd: sudo filebeat setup --pipelines --modules system
      
      # - name:
      #   shell:
      #     cmd: sudo filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["192.168.2.89:9200"]'
      
      - name: Enabling filebeat service
        systemd:
          name: filebeat
          enabled: yes
          daemon_reload: yes
# Start Kibana service
      - name: Starting filebeat service
        systemd:
          name: filebeat
          state: started
          
      - name: Ensure filebeat is running
        systemd: state=started name=filebeat

      - name: restart filebeat
        systemd:
          name: filebeat
          state: restarted


    