---
  - hosts: kibana
    become: true

    tasks:
      - name: update the apt-get
        apt:
          update_cache: yes

      - name: copy my kibana file
        copy:
          src: "kibana.yml"
          dest: /etc/kibana/kibana.yml

      - name: Enabling Kibana service
        systemd:
          name: kibana
          enabled: yes
          daemon_reload: yes
# Start Kibana service
      - name: Starting Kibana service
        systemd:
          name: kibana
          state: started
          
      - name: Ensure Kibana is running
        systemd: state=started name=kibana
